//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMCTJ.BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.corredor = new HashSet<corredor>();
            this.tiempo = new HashSet<tiempo>();
        }
    
        public int categoria_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string alias { get; set; }
    
        public virtual ICollection<corredor> corredor { get; set; }
        public virtual ICollection<tiempo> tiempo { get; set; }
    }
}
