//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMCTJ.BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class corredor
    {
        public corredor()
        {
            this.has_carrera = new HashSet<has_carrera>();
            this.tiempo = new HashSet<tiempo>();
        }
    
        public int corredor_id { get; set; }
        public int club_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string facebook { get; set; }
        public int sexo { get; set; }
        public int categoria_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual club club { get; set; }
        public virtual ICollection<has_carrera> has_carrera { get; set; }
        public virtual ICollection<tiempo> tiempo { get; set; }
    }
}
