//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMCTJ.BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class has_carrera
    {
        public int has_carrera_id { get; set; }
        public int corredor_id { get; set; }
        public int carrera_id { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual corredor corredor { get; set; }
    }
}
