//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMCTJ.BusinessEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carrera> carrera { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<club> club { get; set; }
        public DbSet<corredor> corredor { get; set; }
        public DbSet<has_carrera> has_carrera { get; set; }
        public DbSet<tiempo> tiempo { get; set; }
    }
}
